volumes:
  pg_data:
  static:
  media:
  docs:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    image: arsen551/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - docs:/app/docs
      - ./app/backend/data:/app/data
    depends_on:
      - db

  frontend:
    container_name: foodgram-front
    image: arsen551/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - ../frontend/:/app/result_build/
      - static:/frontend_static
    depends_on:
      - backend

  nginx:
    image: arsen551/foodgram-gateway
    container_name: foodgram-proxy
    env_file: .env
    ports:
      - 8080:80
    volumes:
      - static:/static
      - media:/media
      - docs:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
