volumes:
  pg_data:
  static:
  media:
  docs:

services:
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram-back
    image: arsen551/foodgram_backend
    build: ../backend
    env_file: ../.env
    environment:
      - DJANGO_SETTINGS_MODULE=foodgram_backend.settings
    volumes:
      - static:/backend_static
      - media:/app/media
      - docs:/app/docs
      - ./app/backend/data:/app/data
    depends_on:
      - db

  frontend:
    container_name: foodgram-front
    image: arsen551/foodgram_frontend
    build: ../frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - ../frontend/:/app/result_build/
      - static:/frontend_static
    depends_on:
      - backend


  nginx:
    container_name: foodgram-proxy
    env_file: ../.env
    image: arsen551/foodgram_gateway
    ports:
      - "8080:80"
    volumes:
      - static:/staticfiles
      - media:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
